apiVersion: v1
kind: Service
metadata:
  name: ratings-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: ratings-backend
  type: NodePort
