apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      component: backend
  template:
    metadata:
      labels:
        app: ratings
        component: backend
      annotations:
        balev.eu/author: "Lachezar Balev"
    spec:
      containers:
        - name: ratings-backend
          image: luchob/ratings-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: server-port
          livenessProbe:
            httpGet:
              path: /admin/healthcheck
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /admin/healthcheck
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 30
            timeoutSeconds: 3
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: ratings-config
                  key: mysql.host
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: ratings-config
                  key: mysql.port
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: ratings-config
                  key: mysql.user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
