apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: http://localhost:8080
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
    name: system:node:java2dayskube@kubernetes
current-context: system:node:java2dayskube@kubernetes
preferences: {}
