apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java2days-mysql-pvc
  namespace: java2days
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
