apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-volume
  namespace: java2days
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
